src/AppBundle/Entity/Item.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Item
 *
 * @ORM\Table(name="item")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ItemRepository")
 */
class Item
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", fetch="EAGER")
     */
    private $user;

    /**
     * @ORM\Column(name="image_path", type="string", length=255, unique=false)
     * @Assert\Image()
     */
    private $imagePath = 'images/items/default.jpg';

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\Length(
     *     min="6",
     *     minMessage="The title is below the minimum amount of character",
     *     max="200",
     *     maxMessage="The title is over the maximum amount of character"
     * )
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=1000)
     * @Assert\Length(
     *     min="50",
     *     minMessage="The title is below the minimum amount of character",
     *     max="1000",
     *     maxMessage="The title is over the maximum amount of character"
     * )
     *
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Category")
     */
    private $category;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     */
    private $price;

    /**
     * @var int
     *
     * @ORM\Column(name="quantity", type="integer")
     */
    private $quantity;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_live", type="boolean")
     */
    private $isLive = true;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt = \DateTime::ATOM;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deleted_at", type="datetime", nullable=true)
     */
    private $deletedAt = null;


    /**
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\ItemPromotion", mappedBy="item", fetch="EAGER")
     */
    private $itemDiscount;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param  $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getImagePath()
    {
        return $this->imagePath;
    }

    /**
     * @param mixed $imagePath
     */
    public function setImagePath($imagePath)
    {

        $this->imagePath = $imagePath;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Item
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Item
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set category
     *
     * @param integer $category
     *
     * @return Item
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return int
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set price
     *
     * @param float $price
     *
     * @return Item
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     *
     * @return Item
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    /**
     * @param \DateTime $deletedAt
     */
    public function setDeletedAt(\DateTime $deletedAt)
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * @return bool
     */
    public function isLive(): bool
    {
        return $this->isLive;
    }

    /**
     * @param bool $isLive
     */
    public function setIsLive(bool $isLive)
    {
        $this->isLive = $isLive;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return ItemPromotion
     */
    public function getItemDiscount()
    {
        return $this->itemDiscount;
    }

    /**
     * @param mixed $itemDiscount
     */
    public function setItemDiscount($itemDiscount)
    {
        $this->itemDiscount = $itemDiscount;
    }

    public function getPriceWithDiscount()
    {
        if ($this->itemDiscount == null)
        {
            return $this->price;
        }
        else
        {
            $now = new \DateTime('now');
            if ($now >= $this->getItemDiscount()->getStartDate() && $now <= $this->getItemDiscount()->getEndDate())
                return $this->price - $this->price * ($this->getItemDiscount()->getDiscount() / 100);
            else
                return $this->price;
        }
    }
}

src/AppBundle/Form/ItemType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ItemType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'placeholder' => 'Minimum of 10 characters'
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'placeholder' => 'Minimum of 50 characters',
                    'class' => 'noresize'
                ]
            ])
            ->add('category', null)
            ->add('price', MoneyType::class, [
                'currency' => "USD"
            ])
            ->add('quantity', NumberType::class)
            ->add('imagePath', FileType::class, [
                'label_attr' => [
                    'class' => 'btn btn-block btn-primary btn-file'
                ],
                'attr' => [
                    'class' => 'hidden',
                    'accept' => 'image/*'
                ],
                'data_class' => null,
                'required' => false
            ])
            ->add('isLive', null, [
                'attr' => [
                    'class' => 'bg-success'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-lg btn-success btn-block'
                ]
            ]);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Item'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_item';
    }


}

src/AppBundle/Controller/ItemController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Item;
use AppBundle\Entity\Purchase;
use AppBundle\Form\EditorItemEditType;
use AppBundle\Form\ItemType;
use AppBundle\Form\ResellItemType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;


class ItemController extends Controller
{
    private function uploadPicture(Item $item)
    {
        $file = $item->getImagePath();
        $path = '/../web/images/items/';
        $filename = md5($item->getName() . $item->getCategory() . $this->getUser()->getUsername());
        if (file_exists($this->get('kernel')->getRootDir() . $path . $filename . '.png'))
        {
            unlink($this->get('kernel')->getRootDir() . $path . $filename . '.png');
        }
        $file->move(
            $this->get('kernel')->getRootDir() . $path,
            $filename . '.png'
        );
        $item->setImagePath('images/items/' . $filename . '.png');
    }

    /**
     * @Route("/item/add", name="item_add")
     * @Template()
     *
     * @param Request $request
     */
    public function itemAddAction(Request $request)
    {

        if (!$this->getUser()->isEditor())
        {
            return $this->redirectToRoute('item_all');
        }

        $form = $this->createForm(ItemType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){

            /** @var Item $item */
            $item = $form->getData();

            $item->setCreatedAt(new \DateTime('now'));

            $item->setUser($this->getUser());

            if ($item->getImagePath() != null)
            {
                $this->uploadPicture($item);
            } else {
                $item->setImagePath('images/items/default.jpg');
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($item);
            $em->flush();

            return $this->redirectToRoute('item_all', [
                'info' => $item
            ]);
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route("/", name="item_all")
     * @Template()
     */
    public function itemShowAllAction(Request $request)
    {
        $paginator = $this->get('knp_paginator');

        $requestOrder = $request->query->get('orderBy');
        $requestIn = $request->query->get('in');

        if( $requestOrder != 'createdAt' &&
            $requestOrder != 'price' &&
            $requestOrder != 'name')
        {
            $orderBy = 'createdAt';
        }
        elseif ($requestOrder == null)
        {   $orderBy = 'createdAt'; }
        else
        {   $orderBy = $requestOrder; }

        if ($requestIn != 'asc' && $requestIn != 'desc')
        {   $in = 'desc'; }
        elseif ($requestIn == null)
        {   $in = 'desc'; }
        else
        {   $in = $requestIn; }


        $items = $paginator->paginate(
            $this->getDoctrine()->getRepository('AppBundle:Item')->orderItems($orderBy, $in),
            $request->query->getInt('page', 1),
            $request->query->getInt('limit', 9)
        );

        return [
            'items' => $items
        ];
    }

    /**
     * @Route("/item/{id}", name="item_show", requirements={"id": "\d+"})
     * @Template()
     */
    public function itemShowAction($id)
    {
        /** @var Item $item */
        $item = $this->getDoctrine()->getRepository('AppBundle:Item')->find($id);

        if ($item->getDeletedAt() != null && !$this->getUser()->isAdmin())
            return $this->redirectToRoute('item_all');

        if (!$item->isLive() && (!$this->getUser()->isAdmin() && $item->getUser()->getId() != $this->getUser()->getId()))
            return $this->redirectToRoute('item_all');

        return [
            'item' => $item
        ];
    }

    /**
     * @Route("/item/{id}/edit", name="item_edit", requirements={"id": "\d+"})
     * @Template()
     */
    public function itemEditAction(Request $request, $id)
    {

        $item = $this->getDoctrine()->getRepository('AppBundle:Item')->find($id);

        if (!$this->getUser())
        {
            return $this->redirectToRoute('item_all');
        }
        if (!$this->getUser()->isEditor())
        {
            if ($item->getUser()->getId() != $this->getUser()->getId())
            {
                return $this->redirectToRoute('item_all');
            }
        }

        $itemPath = $item->getImagePath();

        if ($item == null) { $this->redirectToRoute('item_all'); }

        $user = $item->getUser();
        if ($user->getId() != $item->getUser()->getId()) { $this->redirectToRoute('item_all'); }

        if ($this->getUser()->isAdmin())
        {
            $form = $this->createForm(ItemType::class, $item);
        }
        elseif (!$this->getUser()->isAdmin() && $this->getUser()->isEditor())
        {
            $form = $this->createForm(EditorItemEditType::class, $item);
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            if ($form->has('imagePath') &&
                $form->get('imagePath')->getData() != '' && $form->get('imagePath')->getData() != null) {
                $this->uploadPicture($item);
            }
            else {
                $item->setImagePath($itemPath);
            }

            $item->setUser($user);

            $em = $this->getDoctrine()->getManager();
            $em->persist($item);
            $em->flush();

            return $this->redirectToRoute('item_show', [ 'id' => $item->getId() ]);
        }

        return [
            'item' => $item,
            'form' => $form->createView()
        ];
    }

    /**
     * @Route("/item/{id}/delete", name="item_delete")
     * @Method("POST")
     */
    public function itemDeleteProcess(Item $item)
    {
        if (!$this->getUser()->isEditor())
        {
            return $this->redirectToRoute('item_all');
        }

        $em = $this->getDoctrine()->getManager();

        $carts = $em->getRepository('AppBundle:Cart')->findBy([ 'item' => $item->getId()]);

        foreach ($carts as $cart)
        {
            $em->remove($cart);
        }

        $item->setDeletedAt(new \DateTime('now'));

        $em->persist($item);
        $em->flush();
        return $this->redirectToRoute("user_profile", [ 'id' => $this->getUser()->getId() ]);
    }

    /**
     * @Route("/item/{id}/status", name="change_item_status")
     * @Method("POST")
     */
    public function setIsLiveAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $item = $em->getRepository('AppBundle:Item')->find($id);

        $item->setIsLive(!$item->isLive());
        $em->persist($item);
        $em->flush();

        return $this->redirectToRoute('item_show', [ 'id' => $item->getId() ] );
    }


    /**
     * @Route("/item/{id}/resell", name="item_resell")
     * @Method("POST")
     * @Template()
     */
    public function reSellAction(Purchase $purchase, Request $request)
    {
        if ($purchase->isResold())
        {
            return $this->redirectToRoute('profile_purchases', [ 'id' => $this->getUser()->getId() ]);
        }

        $em = $this->getDoctrine()->getManager();

        $item = clone $purchase->getItem();

        $item->setId(null);
        $item->setQuantity($purchase->getQuantity());
        $item->setUser($this->getUser());

        $form = $this->createForm(ResellItemType::class, $item);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $item = $form->getData();

            $purchase->setResold(true);
            $item->setName('[Resold] ' . $item->getName());

            $em->persist($item);
            $em->flush();

            return $this->redirectToRoute('profile_purchases', ['id' => $this->getUser()->getId()]);
        }

        return [
            'form' => $form->createView()
        ];
    }

}

src/AppBundle/Resources/views/Item/itemAdd.html.twig
{% extends 'base.html.twig' %}

{% block title %}The Stocks: Add Item{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
            {{ form_start(form, { 'attr': { 'class': 'panel panel-default' } }) }}

                <div class="panel-body">
                    {{ form_widget(form) }}
                </div>

            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Item/itemEdit.html.twig
{% extends 'base.html.twig' %}

{% dump(item) %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                {{ form_start(form, { 'attr': { 'class': 'panel panel-default' } }) }}

                <div class="panel-body">
                    {{ form_widget(form) }}
                </div>

                {{ form_end(form) }}
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Item/itemShow.html.twig
{% extends 'base.html.twig' %}

{% if item is not empty %}
    {% block title %}The Stocks: {{ item.name }}{% endblock %}
{% endif %}

{% dump(item) %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-6 col-md-6 col-md-offset-3">
                <div class="thumbnail">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <img class="thumbImage itemImage" src="{{ asset(item.imagePath) }}">
                        </div>
                        <div class="panel-body">

                            <div class="caption">
                                <h2 class="center-text">{{ item.name }}</h2>
                                <h5 class="text-center">In stock: {{ item.quantity }}</h5>
                                <h3 class="center-text"><sub>{{ item.category }}</sub></h3>
                                <p>{{ item.description | capitalize}}</p>
                            </div>

                            {% if item.priceWithDiscount != item.price %}
                                <h3 class="center-text">Discount: {{ item.itemDiscount.discount }}%</h3>
                            {% endif %}


                            {% if item.priceWithDiscount != item.price %}
                                <h1 class="center-text">{{ item.priceWithDiscount|number_format(2, '.') }} lv.</h1>
                                <h3 class="center-text"><sub>Original Price: {{ item.price|number_format(2, '.') }} lv.</sub></h3>
                            {% else %}
                                <h1 class="center-text">{{ item.price | number_format(2, '.') }} lv.</h1>
                            {% endif %}
                        </div>
                    </div>

                    {% if app.user %}
                        {% if item.user.id != app.user.id %}
                            <form class="row" method="post" action="{{ path('cart_add', { 'id': item.id}) }}">
                                <div class="col-md-8">
                                    <input class="form-control field" name="quantity" type="number" placeholder="Quantity" min="1" max="{{ item.quantity }}">
                                </div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-block btn-success btn-lg">Add to cart</button>
                                </div>
                            </form>
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            {% if app.user %}
                {% if item.user.id == app.user.id or app.user.isEditor() %}
                    <div class="col-sm-6 com-lg-6 col-md-6 col-md-offset-3">
                        <form method="post" action="{{ path('change_item_status', {id: item.id }) }}">
                            {% if item.isLive() %}
                                <button class="btn btn-danger btn-lg btn-block">Take off market</button>
                            {% else %}
                                <button class="btn btn-success btn-lg btn-block">Put on the market</button>
                            {% endif %}
                        </form>
                        <br>
                        <form method="post" action="{{ path('item_delete', { id: item.id }) }}">
                            <button class="btn btn-danger btn-lg btn-block" type="submit">Remove</button>
                        </form>
                {% endif %}
                {% if app.user.isEditor() %}
                        <br>
                        <form method="post" action="{{ path('add_item_promotion', {id: item.id}) }}">
                            <button class="btn btn-info btn-lg btn-block">Give Promotion</button>
                        </form>
                        <br>
                        <a href="{{ path('item_edit', { id: item.id }) }}" class="btn btn-primary btn-lg btn-block">Edit</a>
                {% endif %}
                    </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Item/itemShowAll.html.twig
{% extends 'base.html.twig' %}

{% dump(items) %}

{% block body %}

    <h1 class="text-center">The Stocks!</h1>
    <hr>
    <div class="container">
        <div class="dropdown">
            <button class="btn btn-lg btn-default dropdown-toggle" type="button" data-toggle="dropdown">Order By
                <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="?orderBy=price&in=asc">Price Ascending</a></li>
                <li><a href="?orderBy=price&in=desc">Price Descending</a></li>
                <li class="divider"></li>
                <li><a href="?orderBy=name&in=asc">A - Z</a></li>
                <li><a href="?orderBy=name&in=desc">Z - A</a></li>
                <li class="divider"></li>
                <li><a href="?orderBy=createdAt&in=desc">New to old</a></li>
                <li><a href="?orderBy=createdAt&in=asc">Old to New</a></li>
            </ul>
        </div>

        <br>

        <div class="row">
            {% for item in items %}

                <div class="col-sm-4 col-lg-4 col-md-4 itemCard">
                    <div class="thumbnail">
                        <a href="{{ path('item_show', { 'id': item.id }) }}"><img class="thumbImage" src="{{ asset(item.imagePath) }}"></a>
                        <div class="caption">
                            <h4>
                                <a target="_blank" href="{{ path('item_show', { 'id': item.id}) }}">
                                    {{ item.name|length > 20 ? item.name|slice(0, 20) ~ '...' : item.name }}
                                </a>
                            </h4>
                            <p>{{ item.description|length > 30 ? item.description|slice(0, 30) ~ '...' : item.description }}</p>

                            {% if item.quantity != 0 %}
                                <div class="row">
                                    <div class="col-md-12">
                                        {% if item.priceWithDiscount == item.price %}
                                                <h4 class="bg-success">Price: {{ item.price|number_format(2, '.') }} lv.</h4>
                                        {% else %}
                                            <h4 class="bg-success">Price: {{ item.priceWithDiscount|number_format(2, '.') }} lv.
                                                <span class="bg-danger">
                                                    <strike>
                                                        {{ item.price|number_format(2, '.') }}
                                                    </strike> lv.
                                                </span>
                                                <sub>{{ item.itemDiscount.discount }}% Off!</sub>
                                            </h4>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <h5>
                                            In Stock: {{ item.quantity }}
                                            <a href="{{ path('user_profile', {'id': item.user.id}) }}" class="pull-right">
                                                {{ item.user.username }}
                                            </a>
                                        </h5>
                                    </div>
                                </div>

                            {% else %}
                                <h4 class="pull-right bg-danger">Out of Stock</h4>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="navigatior">
            {{ knp_pagination_render(items) }}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Item/itemUpdate.html.twig
{% extends 'base.html.twig' %}

{% dump(item) %}

{% block body %}
    {{ form }}
{% endblock %}

src/AppBundle/Resources/views/Item/reSell.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            {{ form_start(form)}}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block title %}

{% endblock %}